// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "PSArchive Home", "www.psarchive.tk  www.psarchive.tk  Keeping your consoles alive!  www.psarchive.tk  www.psarchive.tk  WEBSITE UNDER CONSTRUCTION  PSArchive for the PSP v3.0 Released!  Visit http //www.psarchive.tk/downloads to get started  PSArchiveStore  Scan with CashApp to Donate!  Thank You! PSPMav for creating this video   PSArchive Store PS3 3.1.0 Released!  Visit http //www.psarchive.tk/ps3 to get started   ", "");
   this[database_length++] = new SearchPage("pcgui.html", "Untitled Page", "www.psarchive.tk  www.psarchive.tk  Keeping your consoles alive!  www.psarchive.tk  www.psarchive.tk  WEBSITE UNDER CONSTRUCTION   ", "");
   this[database_length++] = new SearchPage("downloads.html", "Untitled Page", "www.psarchive.tk  www.psarchive.tk  Keeping your consoles alive!  www.psarchive.tk  www.psarchive.tk  WEBSITE UNDER CONSTRUCTION  PSArchiveStore  Scan with CashApp to Donate!  Interactive PSP Preview  PSArchive Store for PSP  Download  App will display under Internet Radio   PSArchive Store for PS3  App in development!  For now use the Internet Browser to browse www.psarchive.tk/ps3    ", "");
   this[database_length++] = new SearchPage("psp.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  Store Top  Donate via CashApp  The Simpsons Game  Playstation 3   PSP   Donate via CashApp  Thank you for visiting the PSArchive Store! We hope you enjoy your stay Try out the PS3 Portal for full access to our library   ", "");
   this[database_length++] = new SearchPage("pspgui.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive   ", "");
   this[database_length++] = new SearchPage("pspdownloads.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  All Downloads   ", "");
   this[database_length++] = new SearchPage("psplist.html", "Untitled Page", "Crash Bandicoot  The Wrath of Cortex  Playstation 3   Guitar Hero II  Deluxe  Playstation 3   Manhunt  Playstation 3   The Warriors  Playstation 3   PSP   LEGO Indiana Jones  The Original Adventures  Playstation 3   YouTube  Playstation 3   The Godfather  The Don's Edition  Playstation 3   MediEvil  Resurrection  PSP   Ace Combat X  Skies of Deception  PSP   Total Overdose  Playstation 3   The Sims 2  Playstation 3   PSP   Red Dead Revolver  Playstation 3   MotoGP  Playstation 3   PSP   WWE SvR 2008  Playstation 3   PSP   Manhunt 2  Playstation 3   PSP   Rockband 2  Playstation 3   Mega Man  Powered Up  PSP   NickToons Racing  Playstation 3   Super Mario 64 HD  Playstation 3   The Sims  Playstation 2   Available on  PS3  The Sims  Playstation 3   Grand Theft Auto  Vice City Stories  Playstation 2   Available on  PS3   PSP  Grand Theft Auto  Vice City Stories  Playstation 3   PSP   Grand Theft Auto  San Andreas  Playstation 2   Available on  PS3  Grand Theft Auto  San Andreas  Playstation 3   Need for Speed  Most Wanted  Playstation 3   PSP   Grand Theft Auto  Liberty City Stories  Playstation 3   PSP   The Simpsons Game  Playstation 3   PSP   LEGO Racers  Playstation 3   Scarface  The World is Yours  Playstation 3   Mega Man  Maverick Hunter X  PSP   Ace Combat  Joint Assault  PSP    ", "");
   this[database_length++] = new SearchPage("setup.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  On a PS3 system already set up to use PSFree or a PC/Mac, connect your PSP to the system with a memory card inserted via a Mini-USB cable Click on the links below and save the files to the 'seplugins' folder of your PSP  If it doesn't exist create it   Once all the files have been downloaded to the PSP, reboot it  You're all done! Pick a category from the above menu and download a game of your choosing Games should be saved to the ISO folder   ", "");
   this[database_length++] = new SearchPage("ps3.html", "", "PSArchive.tk Store  Games and apps for your PS3 and PSP!  Store Top  For best user experience, it's recommended to open your Internet Browser Menu and select the following   View   Maximum Size Tools   Display Area   Full Pixel  User  Select  Exit  v3.1.1   Haloween   PSArchive   Donate via CashApp   ", "");
   this[database_length++] = new SearchPage("alldownloads.html", "Untitled Page", "Featured Downloads  All Downloads   ", "");
   this[database_length++] = new SearchPage("ps3list.html", "Untitled Page", "The Sims  Playstation 2   Available on  PS3  Total Overdose  Playstation 3   Crash Bandicoot  The Wrath of Cortex  Playstation 3   The Sims  Playstation 3   Grand Theft Auto  Vice City Stories  Playstation 2   Available on  PS3   PSP  The Sims 2  Playstation 3   PSP   Guitar Hero II  Deluxe  Playstation 3   Grand Theft Auto  Vice City Stories  Playstation 3   PSP   Grand Theft Auto  San Andreas  Playstation 2   Available on  PS3  Red Dead Revolver  Playstation 3   Manhunt  Playstation 3   Grand Theft Auto  San Andreas  Playstation 3   Need for Speed  Most Wanted  Playstation 3   PSP   MotoGP  Playstation 3   PSP   The Warriors  Playstation 3   PSP   Grand Theft Auto  Liberty City Stories  Playstation 3   PSP   LEGO Indiana Jones  The Original Adventures  Playstation 3   The Simpsons Game  Playstation 3   PSP   WWE SvR 2008  Playstation 3   PSP   YouTube  Playstation 3   LEGO Racers  Playstation 3   Manhunt 2  Playstation 3   PSP   The Godfather  The Don's Edition  Playstation 3   Scarface  The World is Yours  Playstation 3   Rockband 2  Playstation 3   MediEvil  Resurrection  PSP   Mega Man  Maverick Hunter X  PSP   Mega Man  Powered Up  PSP   Ace Combat X  Skies of Deception  PSP   Ace Combat  Joint Assault  PSP   NickToons Racing  Playstation 3   Super Mario 64 HD  Playstation 3   Games  Apps   Homebrew   Other  Movian  Playstation 3   ezTV mod  Movian Plugins   Alone in the Dark  The New Nightmare  Playstation 3   Grand Theft Auto  San Andreas  Playstation 2   Available on  PS3  Resident Evil  Playstation 3   Apps   Homebrew   More   ", "");
   this[database_length++] = new SearchPage("featured.html", "Untitled Page", "Featured Downloads  All Downloads   ", "");
   this[database_length++] = new SearchPage("featuredlist.html", "Untitled Page", "Movian  Playstation 3   ezTV mod  Movian Plugins   Top Download Combo!   ", "");
   this[database_length++] = new SearchPage("classicscorner.html", "Untitled Page", "Classics Corner  MediEvil  Resurrection  PSP   Alone in the Dark  The New Nightmare  Playstation 3   Grand Theft Auto  San Andreas  Playstation 2   Available on  PS3  Resident Evil  Playstation 3    ", "");
   return this;
}
